Questão 23
bsallesb/react-components-exercises-1 pull request #19
Opened 2022-03-18 00:14 UTC by bsallesb

23. Crie um componente que retorna um número inteiro aleatório entre 0 e 10

2022-03-18 01:26 UTC, fredsvanelli requested changes

2022-03-18 01:26 UTC, fredsvanelli commented on src/components/Q23RandomNumber/index.tsx
> +};
As operações `-0` e `+0` não estão fazendo nenhuma diferença nessa conta.

E `Math.random()` retorna um resultado aleatório entre 0.00000 e 0.99999, então, da forma que esta implementado, nunca sairá o resultado 10

2022-03-18 17:00 UTC, fredsvanelli commented on src/components/Q23RandomNumber/index.tsx
> +export default Q23RandomNumber;
1- Dessa forma só sairá um resultado entre 0 e 9
2- Como é apenas uma linha, não precisa do `return`

2022-03-21 14:24 UTC, bsallesb commented on src/components/Q23RandomNumber/index.tsx
> +export default Q23RandomNumber;
Sai o 10 sim, eu testei e saiu um 10.

2022-03-21 14:40 UTC, fredsvanelli approved these changes

2022-03-21 16:01 UTC, merged